print r'#include <stdio.h>'
print r''
print r'/* macro */'
print r''
print r''
print r'/* function statement */'
print r''
print r''
print r'int main(int argc, const char * argv[])'
print r'{'
print r''
print r''
print r'	return 0;'
print r'}'
