print r'<!Doctype html>'
print r'<html>'
print r'	<head>'
print r'		<meta charset="utf-8">'
print r'		<meta lang="en">'
print r'		<title></title>'
print r'		<style type="text/css">'
print r'		div#main{'
print r'			width: ;'
print r'			height: ;'
print r'			background: #;'
print r'			margin: 0 auto;'
print r'		}'
print r'		div#header{'
print r'			width: ;'
print r'			height: ;'
print r'			background: #;'
print r'		}'
print r'		div#body{'
print r'			width: ;'
print r'			height: ;'
print r'			background: #;'
print r'		}'
print r'		div#menu{'
print r'			width: ;'
print r'			height: ;'
print r'			background: #;'
print r'			float:left;'
print r'		}'
print r'		div#content{'
print r'			width: ;'
print r'			height: ;'
print r'			background: #;'
print r'			float:left;'
print r'		}'
print r'		div#footer{'
print r'			width: ;'
print r'			height: ;'
print r'			background: #;'
print r'		}'
print r'		</style>'
print r'		<script type="text/javascript">'
print r'			alert("Content.");'
print r'		</script>'
print r'	</head>'
print r'	</body>'
print r'		<div id="main">'
print r'			<div id="header">'
print r'			</div>'
print r''
print r'			<div id="body">'
print r'				<div id="menu">'
print r'				</div>'
print r''
print r'				<div id="content">'
print r'				</div>'
print r'			</div>'
print r''
print r'			<div id="footer">'
print r'			</div>'
print r'		</div>'
print r'	</body>'
print r'</html>'
